<aside class="main-sidebar">
    <section class="sidebar">
        <?= dmstr\widgets\Menu::widget([
            'options' => ['class' => 'sidebar-menu tree', 'data-widget' => 'tree'],
            'items' => [
                ['label' => 'Menu', 'options' => ['class' => 'header']],

                ['label' => 'PDPA', 'icon' => 'book', 'url' => ['site/pdpa'], 'visible' => true],
                ['label' => 'Laman Utama', 'icon' => 'tachometer', 'url' => ['site/dashboard'], 'visible' => true],
                [
                    'label' => 'Instrumen MISI', 'icon' => 'university', 'url' => '#', 'visible' => true,
                    'items' => [
                        [
                            'label' => 'KK-OKU',
                            'icon' => 'wheelchair-alt',
                            'url' => '#',
                            'items' => [
                                ['label' => 'Utama', 'icon' => 'tachometer', 'url' => ['iksokuf/index'], 'visible' => true],
                                ['label' => 'Profil Demografi', 'icon' => 'user', 'url' => ['iksokuf/demografi'], 'visible' => true],
                                ['label' => 'Bahagian A', 'icon' => 'th-large', 'url' => ['iksokuf/bahagian-a'], 'visible' => true],
                                ['label' => 'Bahagian B', 'icon' => 'random', 'url' => ['iksokuf/bahagian-b'], 'visible' => true],
                                ['label' => 'Bahagian C', 'icon' => 'hourglass-start', 'url' => ['iksokuf/bahagian-c'], 'visible' => true],
                                ['label' => 'Bahagian D', 'icon' => 'cloud-download', 'url' => ['iksokuf/bahagian-d'], 'visible' => true],
                                ['label' => 'Bahagian E', 'icon' => 'etsy', 'url' => ['iksokuf/bahagian-e'], 'visible' => true],
                                ['label' => 'Keputusan', 'icon' => 'file-text', 'url' => ['iksokuf/result'], 'visible' => true],
                            ],
                        ],
                        [
                            'label' => 'EA-Malay',
                            'icon' => 'line-chart',
                            'url' => '#',
                            'items' => [
                                ['label' => 'Pengenalan', 'icon' => 'home', 'url' => ['mea/index'], 'visible' => true],
                                ['label' => 'Demografi', 'icon' => 'th-large', 'url' => ['mea/demografi'], 'visible' => true],
                                ['label' => 'Jadual 1', 'icon' => 'th-large', 'url' => ['mea/jadual-1'], 'visible' => true],
                                ['label' => 'Jadual 2', 'icon' => 'th-large', 'url' => ['mea/jadual-2'], 'visible' => true],
                                ['label' => 'Jadual 3', 'icon' => 'th-large', 'url' => ['mea/jadual-3'], 'visible' => true],
                                ['label' => 'Jadual 4', 'icon' => 'th-large', 'url' => ['mea/jadual-4'], 'visible' => true],
                                ['label' => 'Keputusan', 'icon' => 'star-half-o', 'url' => ['mea/skor'], 'visible' => true],
                            ],
                        ],
                        [
                            'label' => 'EA-Malay (v2)',
                            'icon' => 'bar-chart',
                            'url' => '#',
                            'items' => [
                                ['label' => 'Pengenalan', 'icon' => 'home', 'url' => ['mea-two/index'], 'visible' => true],
                                ['label' => 'Demografi', 'icon' => 'th-large', 'url' => ['mea-two/demografi'], 'visible' => true],
                                ['label' => 'Jadual 1', 'icon' => 'th-large', 'url' => ['mea-two/jadual-1'], 'visible' => true],
                                ['label' => 'Jadual 2', 'icon' => 'th-large', 'url' => ['mea-two/jadual-2'], 'visible' => true],
                                ['label' => 'Jadual 3', 'icon' => 'th-large', 'url' => ['mea-two/jadual-3'], 'visible' => true],
                                ['label' => 'Jadual 4', 'icon' => 'th-large', 'url' => ['mea-two/jadual-4'], 'visible' => true],
                                ['label' => 'Keputusan', 'icon' => 'star-half-o', 'url' => ['mea-two/skor'], 'visible' => true],
                            ],
                        ],
                        [
                            'label' => 'TIPI-Malay',
                            'icon' => 'smile-o',
                            'url' => '#',
                            'items' => [
                                ['label' => 'Pengenalan', 'icon' => 'check-square-o', 'url' => ['tipi/index'], 'visible' => true],
                                ['label' => 'Demografi', 'icon' => 'check-square-o', 'url' => ['tipi/demografi'], 'visible' => true],
                                ['label' => 'Jawab Soal Selidik', 'icon' => 'check-square-o', 'url' => ['tipi/questions'], 'visible' => true],
                                ['label' => 'Keputusan', 'icon' => 'check-square-o', 'url' => ['tipi/result'], 'visible' => true],
                            ],
                        ],
                        [
                            'label' => 'BFI-Malay',
                            'icon' => 'user-secret',
                            'url' => '#',
                            'items' => [
                                ['label' => 'Pengenalan', 'icon' => 'user-secret', 'url' => ['bfi/index'], 'visible' => true],
                                ['label' => 'Demografi', 'icon' => 'user-secret', 'url' => ['bfi/demografi'], 'visible' => true],
                                ['label' => 'Jawab Soal Selidik', 'icon' => 'user-secret', 'url' => ['bfi/questions'], 'visible' => true],
                                ['label' => 'Keputusan', 'icon' => 'user-secret', 'url' => ['bfi/result'], 'visible' => true],
                            ],
                        ],
                        [
                            'label' => 'HEXACO-Malay',
                            'icon' => 'user-circle-o',
                            'url' => '#',
                            'items' => [
                                ['label' => 'Pengenalan', 'icon' => 'user-circle-o', 'url' => ['hexaco/index'], 'visible' => true],
                                ['label' => 'Demografi', 'icon' => 'user-circle-o', 'url' => ['hexaco/demografi'], 'visible' => true],
                                ['label' => 'Bahagian 1', 'icon' => 'user-circle-o', 'url' => ['hexaco/bhgn1'], 'visible' => true],
                                ['label' => 'Bahagian 2', 'icon' => 'user-circle-o', 'url' => ['hexaco/bhgn2'], 'visible' => true],
                                ['label' => 'Bahagian 3', 'icon' => 'user-circle-o', 'url' => ['hexaco/bhgn3'], 'visible' => true],
                                ['label' => 'Bahagian 4', 'icon' => 'user-circle-o', 'url' => ['hexaco/bhgn4'], 'visible' => true],
                                ['label' => 'Bahagian 5', 'icon' => 'user-circle-o', 'url' => ['hexaco/bhgn5'], 'visible' => true],
                                ['label' => 'Bahagian 6', 'icon' => 'user-circle-o', 'url' => ['hexaco/bhgn6'], 'visible' => true],
                                ['label' => 'Keputusan', 'icon' => 'user-circle-o', 'url' => ['hexaco/result'], 'visible' => true],
                            ],
                        ],
                        [
                            'label' => 'EQ-Malay',
                            'icon' => 'id-badge',
                            'visible' => true,
                            'url' => '#',
                            'items' => [
                                ['label' => 'Pengenalan', 'icon' => 'id-badge', 'url' => ['eq/index'], 'visible' => true],
                                ['label' => 'Demografi', 'icon' => 'id-badge', 'url' => ['eq/demografi'], 'visible' => true],
                                ['label' => 'Bahagian 1', 'icon' => 'id-badge', 'url' => ['eq/bhgn1'], 'visible' => true],
                                ['label' => 'Bahagian 2', 'icon' => 'id-badge', 'url' => ['eq/bhgn2'], 'visible' => true],
                                ['label' => 'Bahagian 3', 'icon' => 'id-badge', 'url' => ['eq/bhgn3'], 'visible' => true],
                                ['label' => 'Bahagian 4', 'icon' => 'id-badge', 'url' => ['eq/bhgn4'], 'visible' => true],
                                ['label' => 'Bahagian 5', 'icon' => 'id-badge', 'url' => ['eq/bhgn5'], 'visible' => true],
                                ['label' => 'Bahagian 6', 'icon' => 'id-badge', 'url' => ['eq/bhgn6'], 'visible' => true],
                                ['label' => 'Keputusan', 'icon' => 'id-badge', 'url' => ['eq/result'], 'visible' => true],
                            ],
                        ],
                        [
                            'label' => 'EQ-Malay (v2)',
                            'icon' => 'magic',
                            'visible' => true,
                            'url' => '#',
                            'items' => [
                                ['label' => 'Pengenalan', 'icon' => 'magic', 'url' => ['eq2/index'], 'visible' => true],
                                ['label' => 'Demografi', 'icon' => 'magic', 'url' => ['eq2/demografi'], 'visible' => true],
                                ['label' => 'Bahagian 1', 'icon' => 'magic', 'url' => ['eq2/bhgn1'], 'visible' => true],
                                ['label' => 'Bahagian 2', 'icon' => 'magic', 'url' => ['eq2/bhgn2'], 'visible' => true],
                                ['label' => 'Bahagian 3', 'icon' => 'magic', 'url' => ['eq2/bhgn3'], 'visible' => true],
                                ['label' => 'Bahagian 4', 'icon' => 'magic', 'url' => ['eq2/bhgn4'], 'visible' => true],
                                ['label' => 'Bahagian 5', 'icon' => 'magic', 'url' => ['eq2/bhgn5'], 'visible' => true],
                                ['label' => 'Bahagian 6', 'icon' => 'magic', 'url' => ['eq2/bhgn6'], 'visible' => true],
                                ['label' => 'Keputusan', 'icon' => 'magic', 'url' => ['eq2/result'], 'visible' => true],
                            ],
                        ],
                        [
                            'label' => 'EQ-English (v2)',
                            'icon' => 'magic',
                            'visible' => true,
                            'url' => '#',
                            'items' => [
                                ['label' => 'Introduction', 'icon' => 'magic', 'url' => ['eqbi/index'], 'visible' => true],
                                ['label' => 'demographics', 'icon' => 'magic', 'url' => ['eqbi/demografi'], 'visible' => true],
                                ['label' => 'Part 1', 'icon' => 'magic', 'url' => ['eqbi/bhgn1'], 'visible' => true],
                                ['label' => 'Part 2', 'icon' => 'magic', 'url' => ['eqbi/bhgn2'], 'visible' => true],
                                ['label' => 'Part 3', 'icon' => 'magic', 'url' => ['eqbi/bhgn3'], 'visible' => true],
                                ['label' => 'Part 4', 'icon' => 'magic', 'url' => ['eqbi/bhgn4'], 'visible' => true],
                                ['label' => 'Part 5', 'icon' => 'magic', 'url' => ['eqbi/bhgn5'], 'visible' => true],
                                ['label' => 'Part 6', 'icon' => 'magic', 'url' => ['eqbi/bhgn6'], 'visible' => true],
                                ['label' => 'Result', 'icon' => 'magic', 'url' => ['eqbi/result'], 'visible' => true],
                            ],
                        ],
                        [
                            'label' => 'SDTS-PU',
                            'icon' => 'street-view',
                            'visible' => true,
                            'url' => '#',
                            'items' => [
                                ['label' => 'Pengenalan', 'icon' => 'street-view', 'url' => ['sdts/index'], 'visible' => true],
                                ['label' => 'Demografi', 'icon' => 'street-view', 'url' => ['sdts/demografi'], 'visible' => true],
                                ['label' => 'Soal Selidik', 'icon' => 'street-view', 'url' => ['sdts/questions'], 'visible' => true],
                                ['label' => 'Keputusan', 'icon' => 'street-view', 'url' => ['eq2/result'], 'visible' => true],
                            ],
                        ],
                    ],
                ],

                [
                    'label' => 'Admin Dashboard',
                    'icon' => 'user',
                    'url' => '#',
                    'visible' => !Yii::$app->user->isGuest,
                    'items' => [
                        ['label' => 'Senarai', 'icon' => 'list', 'url' => ['admin/index'], 'visible' => !Yii::$app->user->isGuest],
                        ['label' => 'Data', 'icon' => 'table', 'url' => ['admin/data'], 'visible' => !Yii::$app->user->isGuest],
                        ['label' => 'MIPK', 'icon' => 'table', 'url' => ['admin/data-mipk'], 'visible' => !Yii::$app->user->isGuest],
                        ['label' => 'MEA', 'icon' => 'table', 'url' => ['admin/data-mea'], 'visible' => !Yii::$app->user->isGuest],
                        ['label' => 'MEA v2', 'icon' => 'table', 'url' => ['admin/data-mea-two'], 'visible' => !Yii::$app->user->isGuest],
                        ['label' => 'TIPI', 'icon' => 'smile-o', 'url' => ['admin/data-tipi'], 'visible' => !Yii::$app->user->isGuest],
                        ['label' => 'HEXACO', 'icon' => 'user-circle-o', 'url' => ['admin/data-hexaco'], 'visible' => !Yii::$app->user->isGuest],
                        ['label' => 'BFI', 'icon' => 'user-secret', 'url' => ['admin/data-bfi'], 'visible' => !Yii::$app->user->isGuest],
                        ['label' => 'EQ', 'icon' => 'id-badge', 'url' => ['admin/data-eq'], 'visible' => !Yii::$app->user->isGuest],
                        ['label' => 'EQ v2(Domain)', 'icon' => 'magic', 'url' => ['admin/domain-eq2'], 'visible' => !Yii::$app->user->isGuest],
                        ['label' => 'EQ v2(raw-data)', 'icon' => 'magic', 'url' => ['admin/data-eq2'], 'visible' => !Yii::$app->user->isGuest],
                        [
                            'label' => 'SDTS-PU', 'icon' => 'street-view', 'url' => '#', 'visible' => !Yii::$app->user->isGuest,
                            'items' => [
                                ['label' => 'Raw Data', 'icon' => 'list', 'url' => ['admin/data-sdts'], 'visible' => !Yii::$app->user->isGuest],
                            ],
                        ],
                    ]
                ],
            ],
        ]); ?>
    </section>
</aside>